# Generated by Django 3.0.5 on 2020-04-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200408_0922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'attachment', 'verbose_name_plural': 'attachments'},
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='datum',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='dokument',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='attachment',
            old_name='datei',
            new_name='file',
        ),
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('booking', 'document')},
        ),
    ]
